# divisi init: interactively build a config. Nothing is hardcoded; every
# machine-specific value is asked for here and written to a local, gitignored
# config file. Re-run anytime to reconfigure (it shows current values).

_ask()     { local p="$1" d="${2:-}" a; read -r -p "$p${d:+ [$d]}: " a; echo "${a:-$d}"; }
_ask_secret() { local p="$1" a; read -r -s -p "$p: " a; echo >&2; echo "$a"; }
_yn()      { local p="$1" d="${2:-y}" a; read -r -p "$p [${d}]: " a; a="${a:-$d}"; [[ "$a" =~ ^[Yy] ]]; }

divisi_init() {
  local cfg="${DIVISI_CONFIG:-$HOME/.config/divisi/divisi.conf}"
  mkdir -p "$(dirname "$cfg")"
  info "Configuring divisi -> $cfg"
  [ -f "$cfg" ] && warn "a config already exists; answers below replace it"

  local image base state
  image="$(_ask 'Container image name' 'agentbox')"
  base="$(_ask 'Base image' 'registry.fedoraproject.org/fedora:43')"
  state="$(_ask 'Where to keep context homes' "$HOME/.local/share/divisi")"

  echo; info "Which agent CLIs should be blocked on the host? (space separated)"
  local guard; guard="$(_ask 'Guard tools' 'claude codex gemini')"
  local -a guard_names=()
  read -r -a guard_names <<< "$guard"
  [ "${#guard_names[@]}" -gt 0 ] || die "at least one guard tool is required"
  local tool
  for tool in "${guard_names[@]}"; do
    [[ "$tool" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]] || die "invalid guard tool name: $tool"
  done

  echo; local n; n="$(_ask 'How many contexts' '3')"
  [[ "$n" =~ ^[1-9][0-9]*$ ]] || die "context count must be a positive number"
  [[ "$state" = /* && "$state" != / ]] || die "context home path must be absolute and cannot be /"
  local -a names=()
  local i nm
  for ((i=1;i<=n;i++)); do
    nm="$(_ask "  name of context $i (e.g. work, personal, scratch)")"
    [[ "$nm" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]] || die "invalid context name: $nm"
    [[ " ${names[*]} " != *" $nm "* ]] || die "duplicate context name: $nm"
    names+=("$nm")
  done

  # Per-context settings, collected into temp files we splice into the config.
  local body="" colors=(1\;31 1\;32 1\;33 1\;34 1\;35)
  local -A api_keys=()
  local idx=0
  for nm in "${names[@]}"; do
    echo; info "== context: $nm =="
    local mount gname gemail gh auth vproj vregion secrets seed
    mount="$(_ask "  host dir to mount (blank = no mount, fully isolated)" '')"
    gname="$(_ask "  git user.name (blank = skip)" '')"
    gemail="$(_ask "  git user.email (blank = skip)" '')"
    gh="$(_ask "  gh account label for your notes (blank = none)" '')"
    echo "  claude auth: [vertex] Google Vertex AI  [claude_ai] Claude.ai login  [api_key] Anthropic API key  [none]"
    auth="$(_ask "  claude auth model" 'claude_ai')"
    vproj=""; vregion=""; seed=""
    case "$auth" in
      vertex)
        vproj="$(_ask '    Vertex project id' '')"
        vregion="$(_ask '    Vertex region' 'us-east5')"
        _yn "    copy host ~/.config/gcloud (ADC) into this context now?" y && seed="gcloud" ;;
      claude_ai)
        local s; s="$(_ask '    seed claude config from host dir (blank = fresh /login later)' '')"
        [ -n "$s" ] && seed="claude:$s" ;;
      api_key)
        local k; k="$(_ask_secret '    Anthropic API key (stored in this context vault only)')"
        [ -n "$k" ] || die "API key cannot be empty"
        api_keys[$nm]="$k" ;;
    esac
    secrets="$(_ask '  secret files to vault, space separated host paths (blank = none)' '')"

    body+="$(printf 'CTX_MOUNT[%q]=%q' "$nm" "$mount")"$'\n'
    body+="$(printf 'CTX_GIT_NAME[%q]=%q' "$nm" "$gname")"$'\n'
    body+="$(printf 'CTX_GIT_EMAIL[%q]=%q' "$nm" "$gemail")"$'\n'
    body+="$(printf 'CTX_GH[%q]=%q' "$nm" "$gh")"$'\n'
    body+="$(printf 'CTX_COLOR[%q]=%q' "$nm" "${colors[$((idx % ${#colors[@]}))]}")"$'\n'
    body+="$(printf 'CTX_CLAUDE_AUTH[%q]=%q' "$nm" "$auth")"$'\n'
    body+="$(printf 'CTX_VERTEX_PROJECT[%q]=%q' "$nm" "$vproj")"$'\n'
    body+="$(printf 'CTX_VERTEX_REGION[%q]=%q' "$nm" "$vregion")"$'\n'
    body+="$(printf 'CTX_SECRETS[%q]=%q' "$nm" "$secrets")"$'\n'
    body+="$(printf 'CTX_SEED[%q]=%q' "$nm" "$seed")"$'\n\n'
    idx=$((idx+1))
  done

  umask 077
  {
    echo "# divisi config - generated by 'divisi init'. Local, user-owned, DO NOT COMMIT."
    printf 'DIVISI_IMAGE=%q\n' "$image"
    printf 'DIVISI_BASE=%q\n' "$base"
    printf 'DIVISI_STATE=%q\n' "$state"
    printf 'DIVISI_UID=%q\n' "$(id -u)"
    printf 'DIVISI_GID=%q\n' "$(id -g)"
    printf 'DIVISI_USER=%q\n' "$(id -un)"
    printf 'DIVISI_GUARD_TOOLS=('
    printf '%q ' "${guard_names[@]}"
    printf ')\n'
    echo
    printf 'CONTEXTS=('
    printf '%q ' "${names[@]}"
    printf ')\n'
    echo "declare -gA CTX_MOUNT CTX_GIT_NAME CTX_GIT_EMAIL CTX_GH CTX_COLOR"
    echo "declare -gA CTX_CLAUDE_AUTH CTX_VERTEX_PROJECT CTX_VERTEX_REGION CTX_SECRETS CTX_SEED"
    echo
    printf '%s' "$body"
  } > "$cfg"
  chmod 600 "$cfg"
  local vault
  for nm in "${!api_keys[@]}"; do
    vault="$state/$nm/.secrets"
    mkdir -p "$vault"
    chmod 700 "$state" "$state/$nm" "$vault"
    printf '%s' "${api_keys[$nm]}" > "$vault/anthropic_api_key"
    chmod 600 "$vault/anthropic_api_key"
  done
  ok "wrote $cfg"
  info "Review it, then run:  divisi apply"
}
