# divisi init: interactively build a config. Nothing is hardcoded; every
# machine-specific value is asked for here and written to a local, gitignored
# config file. Re-run anytime to reconfigure (it shows current values).

_ask()     { local p="$1" d="${2:-}" a; read -r -p "$p${d:+ [$d]}: " a; echo "${a:-$d}"; }
_ask_secret() { local p="$1" a; read -r -s -p "$p: " a; echo >&2; echo "$a"; }
_yn()      { local p="$1" d="${2:-y}" a; read -r -p "$p [${d}]: " a; a="${a:-$d}"; [[ "$a" =~ ^[Yy] ]]; }

divisi_init() {
  local cfg="${DIVISI_CONFIG:-$HOME/.config/divisi/divisi.conf}"
  mkdir -p "$(dirname "$cfg")"
  info "Configuring divisi -> $cfg"
  [ -f "$cfg" ] && warn "a config already exists; answers below replace it"

  local image base state
  image="$(_ask 'Container image name' 'agentbox')"
  base="$(_ask 'Base image' 'registry.fedoraproject.org/fedora:43')"
  state="$(_ask 'Where to keep context homes' "$HOME/.local/share/divisi")"

  echo; info "Which agent CLIs should be blocked on the host? (space separated)"
  local guard; guard="$(_ask 'Guard tools' 'claude codex gemini')"

  echo; local n; n="$(_ask 'How many contexts' '3')"
  local -a names=()
  local i nm
  for ((i=1;i<=n;i++)); do
    nm="$(_ask "  name of context $i (e.g. work, personal, scratch)")"
    [ -n "$nm" ] && names+=("$nm")
  done

  # Per-context settings, collected into temp files we splice into the config.
  local body="" colors=(1\;31 1\;32 1\;33 1\;34 1\;35)
  local idx=0
  for nm in "${names[@]}"; do
    echo; info "== context: $nm =="
    local mount gname gemail gh auth vproj vregion secrets seed
    mount="$(_ask "  host dir to mount (blank = no mount, fully isolated)" '')"
    gname="$(_ask "  git user.name (blank = skip)" '')"
    gemail="$(_ask "  git user.email (blank = skip)" '')"
    gh="$(_ask "  gh account label for your notes (blank = none)" '')"
    echo "  claude auth: [vertex] Google Vertex AI  [claude_ai] Claude.ai login  [api_key] Anthropic API key  [none]"
    auth="$(_ask "  claude auth model" 'claude_ai')"
    vproj=""; vregion=""; seed=""
    case "$auth" in
      vertex)
        vproj="$(_ask '    Vertex project id' '')"
        vregion="$(_ask '    Vertex region' 'us-east5')"
        _yn "    copy host ~/.config/gcloud (ADC) into this context now?" y && seed="gcloud" ;;
      claude_ai)
        local s; s="$(_ask '    seed claude config from host dir (blank = fresh /login later)' '')"
        [ -n "$s" ] && seed="claude:$s" ;;
      api_key)
        local k; k="$(_ask_secret '    Anthropic API key (stored in this context vault only)')"
        seed="apikey:$k" ;;
    esac
    secrets="$(_ask '  secret files to vault, space separated host paths (blank = none)' '')"

    body+="CTX_MOUNT[$nm]=\"$mount\""$'\n'
    body+="CTX_GIT_NAME[$nm]=\"$gname\""$'\n'
    body+="CTX_GIT_EMAIL[$nm]=\"$gemail\""$'\n'
    body+="CTX_GH[$nm]=\"$gh\""$'\n'
    body+="CTX_COLOR[$nm]=\"${colors[$((idx % ${#colors[@]}))]}\""$'\n'
    body+="CTX_CLAUDE_AUTH[$nm]=\"$auth\""$'\n'
    body+="CTX_VERTEX_PROJECT[$nm]=\"$vproj\""$'\n'
    body+="CTX_VERTEX_REGION[$nm]=\"$vregion\""$'\n'
    body+="CTX_SECRETS[$nm]=\"$secrets\""$'\n'
    body+="CTX_SEED[$nm]=\"$seed\""$'\n\n'
    idx=$((idx+1))
  done

  umask 077
  {
    echo "# divisi config - generated by 'divisi init'. Local, user-owned, DO NOT COMMIT."
    echo "DIVISI_IMAGE=\"$image\""
    echo "DIVISI_BASE=\"$base\""
    echo "DIVISI_STATE=\"$state\""
    echo "DIVISI_UID=\"\$(id -u)\""
    echo "DIVISI_USER=\"\$(id -un)\""
    echo "DIVISI_GUARD_TOOLS=($guard)"
    echo
    printf 'CONTEXTS=(%s)\n' "${names[*]}"
    echo "declare -gA CTX_MOUNT CTX_GIT_NAME CTX_GIT_EMAIL CTX_GH CTX_COLOR"
    echo "declare -gA CTX_CLAUDE_AUTH CTX_VERTEX_PROJECT CTX_VERTEX_REGION CTX_SECRETS CTX_SEED"
    echo
    printf '%s' "$body"
  } > "$cfg"
  chmod 600 "$cfg"
  ok "wrote $cfg"
  info "Review it, then run:  divisi apply"
}
